### PR TITLE
AlternateContact and Phone BugFix and Feature Enhancements

### LINKED ISSUE #166: [PE-D][Tester B] Non numeric characters allowed in the edit command
The edit command does not enforce the check for non numeric characters in the phone number

**Command Used**: edit 5 p/123p/123

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: nicholascher/ped#7

### LINKED ISSUE #178: [PE-D][Tester C] a/ tag for add command does not allow for certain alternate contact types
Hello! So far the add command is working very well, however:

When I try this command: `add n/Jim Doe p/98765432 e/jimmy.doe@email.com o/Likes SE. t/NUS t/CS2103 course a/Work Email: jimmy.doe@nus.com`

It gives me this error:

This is very likely due to the "@" symbol, which is common and present in many emails. Hence I would suggest lowering the restrictions for the "Alternate contacts" in the REGEX constraints, as I believe that alternate emails definitely fall under this category.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: oeggy03/ped#4

### LINKED ISSUE #192: AlternateContact not accepting intended values
Right now, `AlternateContact` does not accept values that end with `._-` such as `Telegram: Amy_`. However, this is not the intended effect as it supposed to accept it.

image

### PR DESCRIPTION
**Pull request by rayshawntan**
This PR clears the bugs that are caused by the regex in `Phone.java` and `AlternateContact.java`. This corrects the values that can be accepted by both. UG and `Messages.java` are updated to give better clarity on what can be accepted and what is not.

Closes #178 , fixes #192.

Works towards #166.

### CODE REVIEW

File: src/main/java/swe/context/logic/Messages.java [hunk 1]
```diff
@@ -43,7 +43,8 @@ public final class Messages {
             "\"%s\" is not a valid tag. Tags must be alphanumeric (spaces allowed).";
     private static final String UNFORMATTED_ALTERNATECONTACT_INVALID =
             "\"%s\" is not a valid alternate contact. "
-            + "Alternate contacts must roughly be of the form \"SocialMedia: Username\"";
+            + "Alternate contacts must roughly be of the form \"SocialMedia: Username\" "
+            + "Whitespace is not supported for both SocialMedia and Username and Username only supports ._-";
```
Comment (Cloud7050) [inline src/main/java/swe/context/logic/Messages.java:47]: They may count enhancing the message as a feature enhancement.

File: src/main/java/swe/context/model/contact/Phone.java [hunk 2]
```diff
@@ -12,7 +12,7 @@ public class Phone {
     /*
      * Requires starting with at least 3 of digits.
```
Comment (Cloud7050) [inline src/main/java/swe/context/model/contact/Phone.java:13]: This Javadoc is now outdated. There may be other places that are now outdated.

**Review by Cloud7050 — CHANGES_REQUESTED** [review]

File: src/main/java/swe/context/logic/Messages.java (hunk 1 above)
Comment (Cloud7050) [reply src/main/java/swe/context/logic/Messages.java:47]: Also, is there meant to be a `%n` newline?

Comment (rayshawntan) [reply src/main/java/swe/context/logic/Messages.java]: > They may count enhancing the message as a feature enhancement.

Yeap, rereading on what constitutes as a feature enhancement, this definitely seems more like an enhancement. Have removed it.

File: src/main/java/swe/context/model/contact/Phone.java (hunk 2 above)
Comment (rayshawntan) [reply src/main/java/swe/context/model/contact/Phone.java]: Have amended this.

**Comment by Cloud7050** [comment]
> Closes #166 , #178 , #192

Btw, the above only autocloses the first issue. They would need the "closes" keyword repeated for all of them.

File: src/main/java/swe/context/model/alternate/AlternateContact.java [hunk 3]
```diff
@@ -14,7 +14,7 @@ public final class AlternateContact {
      * Requires a form similar to AlternateContact: name.
      */
     public static final String REGEX_VALID =
-            "^[a-zA-Z\\d]+(?:[a-zA-Z\\d]+)*" + ":\\s([._-]?[a-zA-Z0-9]+)+";
+            "^[a-zA-Z\\d]+(?:[a-zA-Z\\d]+)*" + ":\\s([._-]?[a-zA-Z0-9]?)+";
```
Comment (Cloud7050) [inline src/main/java/swe/context/model/alternate/AlternateContact.java:17]: We may be able to simplify this if we want (refactoring alongside the fix). Draft: `^[a-zA-Z\\d]+: [a-zA-Z\\d\\._-]+$`. I have not checked this. But aside from the Java string escapes, this is a useful site: https://regexr.com/.

Potential bug: If we allow any whitespace (`\s`), users may do something weird like put a zero-width space. It would look different from the other alternates. It may also fail unit test if we test using a newline.

File: docs/UserGuide.md [hunk 4]
```diff
@@ -94,12 +100,15 @@ Duplicate tags are only counted once.
...
+Do note at this moment whitespace is not supported for `TYPE` and `USERNAME` and `USERNAME` supports only `._-`.
 </div>
 
 **Examples:**
 
-- `add n/John Doe p/98765432 e/john.doe@email.com`
+- `add n/John Doe p/98765432 e/john.doe@email.com` 
+(Adds a contact with the name `John Doe`, phone `98765432` and email `john.doe@email.com`)
 - `add n/John Doe p/98765432 e/john.doe@email.com o/Likes SE. t/NUS t/CS2103 course a/Telegram: JohnDoe`
+(Adds a contact with the name `John Doe`, phone `98765432`, email `john.doe@email.com`, note `Likes SE`, tags `NUS` and `CS2103 course` and alternate contact `Telegram: JohnDoe`)
```
Comment (Cloud7050) [inline docs/UserGuide.md:111]: The note in the second part is missing the fullstop.

File: docs/UserGuide.md [hunk 5]
```diff
@@ -94,12 +100,15 @@ Duplicate tags are only counted once.
 <div markdown="span" class="alert alert-info">
 :information_source: **About the alternate contact format:**
 The format for `ALTERNATE_CONTACT` is `TYPE: USERNAME`, roughly looking like `SocialMedia: Username`. Ensure to include a space between the colon and the Username.
+Do note at this moment whitespace is not supported for `TYPE` and `USERNAME` and `USERNAME` supports only `._-`.
```
Comment (Cloud7050) [inline docs/UserGuide.md:103]: - Does  "and `USERNAME` and `USERNAME`" read a bit strangely? Should we add something like a comma?
- Testers may be able to report a bug if it sounds like `USERNAME` *only* supports `._-` (maybe specify that those are the only *special characters* aside from alnum supported or something)

File: docs/UserGuide.md [hunk 6]
```diff
@@ -86,6 +86,12 @@ Should you need to make changes to an existing contact, use the `edit` command a
 **Format:**
 `add n/NAME p/PHONE_NUMBER e/EMAIL [o/NOTE] [t/TAG]... [a/ALTERNATE_CONTACT]...`
 
+<div markdown="span" class="alert alert-info">
+:information_source: **About phone number**
+Phone numbers must contain at least 3 digits. Alphabets and special characters are not accepted.
```
Comment (Cloud7050) [inline docs/UserGuide.md:91]: Should we be clearer in case testers still try to make reports? The regex is changed to strictly only allow digits.

File: src/main/java/swe/context/model/contact/Phone.java [hunk 7]
```diff
@@ -10,9 +10,9 @@
  */
 public class Phone {
     /*
-     * Requires starting with at least 3 of digits.
+     * Requires at least 3 digits.
      */
-    public static final String REGEX_VALID = "^\\d{3,}.*$";
+    public static final String REGEX_VALID = "^\\d{3,}";
```
Comment (Cloud7050) [inline src/main/java/swe/context/model/contact/Phone.java:15]: For consistency, perhaps we should keep the ending `$` (matches end of string, like an opposite of `^`). Java's `matches()` matches the full string, but `find()` does not.

File: docs/DeveloperGuide.md [hunk 8]
```diff
@@ -452,3 +452,11 @@ testers are expected to do more *exploratory* testing.
 ## **Appendix: Planned enhancements**
 
 //TODO this is for countering known feature flaws to help grading, after the feature freeze. We can only list `4 members x 2 = 8` enhancements here
+
+* The current implementation of `Phone` allow users to include very long numbers that might not be a number that 
+actually exist some part of the world. We also intend to allow users to include the `+` prefix to allow users to indicate
```
Comment (Cloud7050) [inline docs/DeveloperGuide.md:457]: Typo in "number that actually exist some part of the world".

File: docs/DeveloperGuide.md [hunk 9]
```diff
@@ -452,3 +452,11 @@ testers are expected to do more *exploratory* testing.
...
+country codes as well. The invalid message `Phone numbers must start with at least 3 digits.` as a result will need to be
```
Comment (Cloud7050) [inline docs/DeveloperGuide.md:458]: That message is the way it is because users were allowed to put other characters after those 3 digits. I think if we are changing the regex due to a bug, it is then fitting to also fix the message accordingly. (The planned enhancement may then further edit the message again.)

File: docs/DeveloperGuide.md [hunk 10]
```diff
@@ -452,3 +452,11 @@ testers are expected to do more *exploratory* testing.
...
+updated to reflect on this change.
```
Comment (Cloud7050) [inline docs/DeveloperGuide.md:459]: Is there a typo in the "on" of "reflect on"?

File: docs/DeveloperGuide.md [hunk 11]
```diff
@@ -452,3 +452,11 @@ testers are expected to do more *exploratory* testing.
...
+* The current implementation of `AlternateContact` does not allow users to include whitespace in `TYPE` and `USERNAME`
```
Comment (Cloud7050) [inline docs/DeveloperGuide.md:460]: Typo where "and `USERNAME`" is repeated twice.

File: docs/DeveloperGuide.md [hunk 12]
```diff
@@ -452,3 +452,11 @@ testers are expected to do more *exploratory* testing.
 ## **Appendix: Planned enhancements**
 
 //TODO this is for countering known feature flaws to help grading, after the feature freeze. We can only list `4 members x 2 = 8` enhancements here
+
+* The current implementation of `Phone` allow users to include very long numbers that might not be a number that 
+actually exist some part of the world. We also intend to allow users to include the `+` prefix to allow users to indicate
+country codes as well. The invalid message `Phone numbers must start with at least 3 digits.` as a result will need to be
+updated to reflect on this change.
+* The current implementation of `AlternateContact` does not allow users to include whitespace in `TYPE` and `USERNAME` 
+and `USERNAME` only supports `._-` symbols. We intend to allow users to include whitespace as well as more `USERNAME`
```
Comment (Cloud7050) [inline docs/DeveloperGuide.md:461]: Similar to other comments, is there room to be more specific to avoid testers trying to report flaws in the planned enhancement?

- Eg "symbols" is mentioned, which we can understand means special characters alongside the alnum, but will testers interpret it the same?
- Eg how will testers interpret "more `USERNAME`"?

**Review by Cloud7050 — CHANGES_REQUESTED** [review]

File: docs/UserGuide.md (hunk 4 above)
Comment (rayshawntan) [reply docs/UserGuide.md:111]: Ah, my bad. Have amended this.

File: src/main/java/swe/context/model/alternate/AlternateContact.java (hunk 3 above)
Comment (rayshawntan) [reply src/main/java/swe/context/model/alternate/AlternateContact.java:17]: > We may be able to simplify this if we want (refactoring alongside the fix). Draft: `^[a-zA-Z\\d]+: [a-zA-Z\\d\\._-]+$`. I have not checked this. But aside from the Java string escapes, this is a useful site: https://regexr.com/.

I don't think this is possible to be done without risking chance of this considering as a feature enhancement.

image

> Potential bug: If we allow any whitespace (`\s`), users may do something weird like put a zero-width space. It would look different from the other alternates. It may also fail unit test if we test using a newline.
 
`\s` does not allow zero-width space from my understanding.

Comment (Cloud7050) [reply src/main/java/swe/context/model/alternate/AlternateContact.java:17]: I feel like it fits this pointer. We are not tweaking the check's behaviour (aside from the bug fix), rather, we are refactoring the regex, ie refactoring the code:

image

Personally I think it is safe to do.

---

TIL `\s` does not match zws, thanks. Perhaps another example would be pasting in `	` (tab) to sabotage the application. The alternate would still look wider than the others, since only one whitespace character is allowed. And I feel the newline point still stands.

Names on the other hand (and by extension, tags) only allow normal spaces.

Comment (Cloud7050) [reply src/main/java/swe/context/model/alternate/AlternateContact.java:17]: image

Comment (Cloud7050) [reply src/main/java/swe/context/model/alternate/AlternateContact.java:17]: image

(Comparison to PR regex, with added `$` to behave like `matches()`)

Comment (Cloud7050) [reply src/main/java/swe/context/model/alternate/AlternateContact.java:17]: During testing, I think I found a regression with the PR regex. Since everything in the capturing group is optional, empty values are once again allowed:

image

Comment (rayshawntan) [reply src/main/java/swe/context/model/alternate/AlternateContact.java:17]: hmm, since its okay, will update the regex then

File: docs/UserGuide.md [hunk 13]
```diff
@@ -96,12 +102,15 @@ Duplicate tags are only counted once.
 <div markdown="span" class="alert alert-info">
 :information_source: **About the alternate contact format:**
 The format for `ALTERNATE_CONTACT` is `TYPE: USERNAME`, roughly looking like `SocialMedia: Username`. Ensure to include a space between the colon and the Username.
+Do note at this moment whitespace is not supported for `TYPE` and `USERNAME`. `USERNAME` supports only special characters `.`, `_` and `-`.
```
Comment (Cloud7050) [inline docs/UserGuide.md:105]: Re: Taking this line on its own:

> `USERNAME` supports only special characters `.`, `_` and `-`.

When read a certain way, it could sound like username literally only supports those 3 characters and nothing else.

As we are refactoring the regex to be clearer, would it be good to clarify w.r.t. alnum?

File: docs/DeveloperGuide.md [hunk 14]
```diff
@@ -442,10 +442,10 @@ testers are expected to do more *exploratory* testing.
...
-1. The current implementation of `AlternateContact` does not allow users to include whitespace in `TYPE` and `USERNAME`
-  and `USERNAME` only supports certain special characters. We intend to allow users to include whitespace in `TYPE` and
-  `USERNAME`. `USERNAME` will also be enhanced to include other special characters that are not supported currently. This
-  will allow `AlternateContact` to be used more flexibly.
+1. The current implementation of `Phone` allows users to include very long numbers that might not be a valid number in the
+   world. We also intend to allow users to include the `+` prefix to allow users to indicate country codes as well. The
+   invalid message `Phone numbers must start with at least 3 digits.` will need to be updated to reflect this enhancement.
+1. The current implementation of `AlternateContact` does not allow users to include whitespace in `TYPE` and `USERNAME`.
+   `USERNAME` currently only supports alphanumeric and certain special characters. We intend to allow users to include 
+   whitespace in`TYPE` and `USERNAME`. `USERNAME` will also be enhanced to include other special characters that are not
```
Comment (Cloud7050) [inline docs/DeveloperGuide.md:450]: > in`TYPE`

There is a missing space here.

**Review by Cloud7050 — CHANGES_REQUESTED** [review]

**Review by Cloud7050 — APPROVED** [review]

**Review by bwangpj — APPROVED** [review]
